### ISSUE TITLE
pycg can‘t find the real function 

### ISSUE THREAD

**Issue by Gzxl** [vitsalis/PyCG#28]
repo：https://github.com/PaddlePaddle/PaddleClas
cmd :pycg --package ppclas $(find ppclas -type f -name "*.py") -o ppclas.json
error: funciton:ppcls/arch/backbone/base/theseus_layer.py is subclass paddle.nn.Layer
           the function train is from nn.Layer
           but the ppclas.json not show this message
e.g.:
        
<img width="804" alt="image" src="https://user-images.githubusercontent.com/6359205/162923731-00ab235c-210c-4a74-b453-0b73aa86bd2b.png">

**Comment by vitsalis** [comment]
PyCG can only analyze the code that it has been given. It can't know what the parent class contains and therefore cannot identify that particular call.

**Comment by vitsalis** [comment]
This happens because PyCG tries to do some basic inference about what was the external function that was called based on the imports. More specifically, when PyCG sees something along the lines of
```
from xyz.pkg import smth
smth()
```

it can understand that there was a call to the `smth()` function inside the `xyz.pkg` module. However, we can't go further than that because we do not have the code for `xyz.pkg`.
