### ISSUE TITLE
Can pycg analyze a function call chain?

### ISSUE THREAD

**Issue by takashi-ishio** [vitsalis/PyCG#9]
Thank you for making the interesting tool public!   I am reading the ICSE paper and trying to use this tool.

I have one question about the behavior of pycg.
I have the following code `example.py`:
```python
class C:
        def __init__(self):
                pass

        def m(self):
                return "x({0})"

obj = C()
print(obj.m().format(1))
```
I executed `pycg example.py`.

I expected that pycg reports that the `example` file calls `str.format` (called in the bottom line) because the function body is included in the analysis.  

However, pycg resulted in:
```
{"example": ["example.C.m", "example.C.__init__", "<builtin>.print"], "example.C.__init__": [], "example.C.m": [], "<builtin>.print": []}
```
The `str.format` function is not included in the result.

Do I miss any important options?

**Comment by vitsalis** [comment]
Currently, PyCG does not support the identification of calls to built-in methods based on the type of a variable. In order to do that, we need some kind of a model of built-in methods and functions and their effects. Specifically, in the case of your example, we need to know that variables that are strings have an attribute named `format` which can be called. As you understand, there are many such methods in Python and in order to properly analyze them we need an internal representation of these functions and their effects (e.g. strings define a `format` method and `str.format` returns a string object).

**Comment by takashi-ishio** [comment]
Thank you for the response, I understand the behavior.
